---
name: Lint all markdown files in docs

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DavidAnson/markdownlint-cli2-action@v9
      with:
        globs: | 
          docs/**/*.md